server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: shipment-service
          uri: lb://shipment-service
          predicates:
            - Path=/shipments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka